### ISSUE TITLE
node:16 docker run in the CI uses node8

### ISSUE THREAD

**Issue by v1v** [elastic/ecs-logging-nodejs#112]
See Trent's comment -> https://github.com/elastic/ecs-logging-nodejs/pull/111#issuecomment-996116946

I tried to reproduce the error locally with:

```
docker run --rm -ti -v $(pwd):/app node:16 /bin/bash
$ cd /app
$ .ci/run-install.sh
$ .ci/run-test.sh
```

but it worked

**Comment by trentm** [comment]
Trying again with https://apm-ci.elastic.co/job/apm-agent-nodejs/job/ecs-logging-nodejs-mbp/job/main/3/

The last successful run was Nov 30th: https://apm-ci.elastic.co/job/apm-agent-nodejs/job/ecs-logging-nodejs-mbp/job/master/
The first failing run was Dec 16th: https://apm-ci.elastic.co/job/apm-agent-nodejs/job/ecs-logging-nodejs-mbp/job/main/1/

We didn't have runs in between because no changes to the repo and there isn't a daily or weekly run.

**Comment by trentm** [comment]
This is consistently breaking in Jenkins CI, but not reproducible locally in docker (as @v1v showed above -- I get the same).

@v1v Is this something that you or someone on the robots team can look into why the difference in Jenkins CI? How is it possible that within:

```groovy
docker.image("node:16").inside("-e HOME=${WORKSPACE}/${BASE_DIR}") {
      sh(label: 'Install dependencies', script: '.ci/run-install.sh')
      sh(label: 'Run tests', script: '.ci/run-test.sh')
    }
```

these node and npm versions are active: `{"node":"8.17.0","npm":"6.13.4"}`?

**Comment by v1v** [comment]
Interestingly I've found where those particular docker images are generated and cached from:

![image](https://user-images.githubusercontent.com/2871786/146732695-6acf2d11-b9af-4c03-b8c9-d58f30ac9a12.png)

In a nutshell, it uses -> https://github.com/elastic/apm-agent-nodejs/blob/master/.ci/docker/node-container/Dockerfile with the `build-args`:

```
docker build --force-rm --build-arg NODE_VERSION=16 -t docker.elastic.co/observability-ci/apm-agent-nodejs:16 .
```

I wonder if something has been cached with the `packer-cache.sh` script somehow, I'll try with `--no-cache` and see if it gets any better

**Comment by trentm** [comment]
Yup, the building of that image definitely looks to be an issue:

```
% docker run --rm -ti docker.elastic.co/observability-ci/apm-agent-nodejs:16 /bin/bash
root@9615f363361e:/app# node --version
v8.17.0
```

@v1v Do you think dropping the `=8` default from https://github.com/elastic/apm-agent-nodejs/blob/master/.ci/docker/node-container/Dockerfile#L1 would help? I notice that the somewhat similar "node-edge-container/Dockerfile" does not have this: https://github.com/elastic/apm-agent-nodejs/blob/master/.ci/docker/node-edge-container/Dockerfile#L14

**Comment by trentm** [comment]
Also, for the record, an example jenkins build for that screenshot above is: https://apm-ci.elastic.co/blue/organizations/jenkins/apm-shared%2Fapm-docker-images-pipeline/detail/apm-docker-images-pipeline/1431/pipeline/63

**Comment by trentm** [comment]
@v1v There is another thing I don't understand. How does `docker.image("node:16").` related to a docker image at `docker.elastic.co/observability-ci/apm-agent-nodejs:16` rather than the public "node:16" image on Docker Hub?

**Comment by v1v** [comment]
> docker.elastic.co/observability-ci/apm-agent-nodejs:16 rather than the public "node:16" image on Docker Hub?

It's a matter of the cache layouts, so the `docker.elastic.co/observability-ci/apm-agent-nodejs:16` is built and then retagged to node:16.

The script in charge is -> https://github.com/elastic/apm-agent-nodejs/blob/ae26f6de8a96fc48631f832891be51d14dc123ea/.ci/packer_cache.sh#L14-L21

**Comment by v1v** [comment]
I just closed https://github.com/elastic/ecs-logging-nodejs/pull/113 with the comment -> https://github.com/elastic/ecs-logging-nodejs/pull/113#issuecomment-998586626

I think once https://github.com/elastic/apm-agent-nodejs/pull/2522 is merged and the `packer_cache.sh` is executed (it runs once a day) then the CI workers will contain the correct cached docker images. This process takes about 1 or 2 days.

**Comment by trentm** [comment]
Oh. After some hunting, I found https://github.com/elastic/infra/blob/master/docs/packer2.0/caching.md
It was not at all clear to me what was going on here before this.

1. I agree that we should remove the tagging of `docker.elastic.co/observability-ci/apm-agent-nodejs:$VER` to `node:$VER`. I think that is subtle, and hence confusing when it breaks.

2. If we remove that, then (if I understand correctly) the apm-agent-nodejs and ecs-logging-nodejs tests will no longer use any of the `docker.elastic.co/observability-ci/apm-agent-nodejs:$VER` images because they specify a `node:$VER` image in which to test.  My guess is that `node:$VER` is used to allow apm-agent-nodejs tests to run both in apm-ci.elastic.co and in GitHub Actions (originally in TravisCI). Is there a reason to have the `docker.elastic.co/observability-ci/apm-agent-nodejs:$VER` images? Could we just stop building them and change ".ci/packer_cache.sh" to `docker pull node:$version` for each version in https://github.com/elastic/apm-agent-nodejs/blob/master/.ci/.jenkins_nodejs.yml?

3. A few of the `docker.elastic.co/observability-ci/apm-agent-nodejs:$VER` images are just broken:

```
% cd .../apm-agent-nodejs
% cat .ci/.jenkins_nodejs.yml | grep -- - | cut -d'"' -f2 | while read ver; do
    echo "# node version in docker.elastic.co/observability-ci/apm-agent-nodejs:$ver"
    docker run --rm docker.elastic.co/observability-ci/apm-agent-nodejs:$ver node --version
done
# node version in docker.elastic.co/observability-ci/apm-agent-nodejs:17
v8.17.0
# node version in docker.elastic.co/observability-ci/apm-agent-nodejs:16
v8.17.0
# node version in docker.elastic.co/observability-ci/apm-agent-nodejs:16.0
v8.17.0
# node version in docker.elastic.co/observability-ci/apm-agent-nodejs:14
v14.18.2
# node version in docker.elastic.co/observability-ci/apm-agent-nodejs:14.0
v14.0.0
# node version in docker.elastic.co/observability-ci/apm-agent-nodejs:12
v12.22.8
# node version in docker.elastic.co/observability-ci/apm-agent-nodejs:12.0
v12.0.0
# node version in docker.elastic.co/observability-ci/apm-agent-nodejs:10
v10.24.1
# node version in docker.elastic.co/observability-ci/apm-agent-nodejs:10.0
v10.0.0
# node version in docker.elastic.co/observability-ci/apm-agent-nodejs:8
v8.17.0
# node version in docker.elastic.co/observability-ci/apm-agent-nodejs:8.6
v8.6.0
```

Those first 3 are broken.  Compare the `docker history` for a working one:

```
% docker history docker.elastic.co/observability-ci/apm-agent-nodejs:14
IMAGE          CREATED        CREATED BY                                      SIZE      COMMENT
ed2a2afccf45   17 hours ago   /bin/sh -c #(nop) WORKDIR /app                  0B
<missing>      17 hours ago   /bin/sh -c node --version && npm --version      0B
<missing>      2 weeks ago    /bin/sh -c #(nop)  CMD ["node"]                 0B
<missing>      2 weeks ago    /bin/sh -c #(nop)  ENTRYPOINT ["docker-entry…   0B
<missing>      2 weeks ago    /bin/sh -c #(nop) COPY file:4d192565a7220e13…   388B
<missing>      2 weeks ago    /bin/sh -c set -ex   && for key in     6A010…   7.72MB
<missing>      2 weeks ago    /bin/sh -c #(nop)  ENV YARN_VERSION=1.22.15     0B
<missing>      2 weeks ago    /bin/sh -c ARCH= && dpkgArch="$(dpkg --print…   101MB
<missing>      2 weeks ago    /bin/sh -c #(nop)  ENV NODE_VERSION=14.18.2     0B
<missing>      2 weeks ago    /bin/sh -c groupadd --gid 1000 node   && use…   333kB
<missing>      2 weeks ago    /bin/sh -c set -ex;  apt-get update;  apt-ge…   561MB
<missing>      2 weeks ago    /bin/sh -c apt-get update && apt-get install…   141MB
<missing>      2 weeks ago    /bin/sh -c set -ex;  if ! command -v gpg > /…   7.82MB
<missing>      2 weeks ago    /bin/sh -c set -eux;  apt-get update;  apt-g…   24.1MB
<missing>      2 weeks ago    /bin/sh -c #(nop)  CMD ["bash"]                 0B
<missing>      2 weeks ago    /bin/sh -c #(nop) ADD file:80aa4dde5bfd685e5…   101MB
```

to a broken one:

```
% docker history docker.elastic.co/observability-ci/apm-agent-nodejs:16
IMAGE          CREATED         CREATED BY                                      SIZE      COMMENT
b62d3beedad0   17 hours ago    /bin/sh -c #(nop) WORKDIR /app                  0B
<missing>      17 hours ago    /bin/sh -c node --version && npm --version      0B
<missing>      31 hours ago    /bin/sh -c #(nop) WORKDIR /app                  0B
<missing>      31 hours ago    /bin/sh -c node --version && npm --version      0B
<missing>      4 days ago      /bin/sh -c #(nop) WORKDIR /app                  0B
<missing>      4 days ago      /bin/sh -c node --version && npm --version      0B
<missing>      5 days ago      /bin/sh -c #(nop) WORKDIR /app                  0B
<missing>      5 days ago      /bin/sh -c node --version && npm --version      0B
<missing>      6 days ago      /bin/sh -c #(nop) WORKDIR /app                  0B
<missing>      6 days ago      /bin/sh -c node --version && npm --version      0B
<missing>      7 days ago      /bin/sh -c #(nop) WORKDIR /app                  0B
<missing>      7 days ago      /bin/sh -c node --version && npm --version      0B
<missing>      8 days ago      /bin/sh -c #(nop) WORKDIR /app                  0B
<missing>      8 days ago      /bin/sh -c node --version && npm --version      0B
<missing>      11 days ago     /bin/sh -c #(nop) WORKDIR /app                  0B
<missing>      11 days ago     /bin/sh -c node --version && npm --version      0B
<missing>      12 days ago     /bin/sh -c #(nop) WORKDIR /app                  0B
<missing>      12 days ago     /bin/sh -c node --version && npm --version      0B
<missing>      13 days ago     /bin/sh -c #(nop) WORKDIR /app                  0B
<missing>      13 days ago     /bin/sh -c node --version && npm --version      0B
<missing>      2 weeks ago     /bin/sh -c #(nop) WORKDIR /app                  0B
<missing>      2 weeks ago     /bin/sh -c node --version && npm --version      0B
<missing>      2 weeks ago     /bin/sh -c #(nop) WORKDIR /app                  0B
<missing>      2 weeks ago     /bin/sh -c node --version && npm --version      0B
<missing>      2 weeks ago     /bin/sh -c #(nop) WORKDIR /app                  0B
<missing>      2 weeks ago     /bin/sh -c node --version && npm --version      0B
<missing>      2 weeks ago     /bin/sh -c #(nop) WORKDIR /app                  0B
<missing>      2 weeks ago     /bin/sh -c node --version && npm --version      0B
<missing>      3 weeks ago     WORKDIR /app                                    0B        buildkit.dockerfile.v0
<missing>      3 weeks ago     RUN /bin/sh -c node --version && npm --versi…   0B        buildkit.dockerfile.v0
<missing>      24 months ago   /bin/sh -c #(nop)  CMD ["node"]                 0B
<missing>      24 months ago   /bin/sh -c #(nop)  ENTRYPOINT ["docker-entry…   0B
<missing>      24 months ago   /bin/sh -c #(nop) COPY file:238737301d473041…   116B
<missing>      24 months ago   /bin/sh -c set -ex   && for key in     6A010…   5.48MB
<missing>      24 months ago   /bin/sh -c #(nop)  ENV YARN_VERSION=1.21.1      0B
<missing>      24 months ago   /bin/sh -c ARCH= && dpkgArch="$(dpkg --print…   60.3MB
<missing>      24 months ago   /bin/sh -c #(nop)  ENV NODE_VERSION=8.17.0      0B
<missing>      24 months ago   /bin/sh -c groupadd --gid 1000 node   && use…   333kB
<missing>      24 months ago   /bin/sh -c set -ex;  apt-get update;  apt-ge…   562MB
<missing>      24 months ago   /bin/sh -c apt-get update && apt-get install…   142MB
<missing>      24 months ago   /bin/sh -c set -ex;  if ! command -v gpg > /…   7.81MB
<missing>      24 months ago   /bin/sh -c apt-get update && apt-get install…   23.3MB
<missing>      24 months ago   /bin/sh -c #(nop)  CMD ["bash"]                 0B
<missing>      24 months ago   /bin/sh -c #(nop) ADD file:8f7dc710e276f54a3…   101MB
```

There is something that broke 2 or 3 weeks ago with the `docker.elastic.co/observability-ci/apm-agent-nodejs` image builds. Perhaps those build machines have the confusing `docker tag docker.elastic.co/observability-ci/apm-agent-nodejs:$ver node$ver` for some versions and new daily builds of those images are accidentally building **on top of themselves**.

**Comment by trentm** [comment]
> 3\. A few of the `docker.elastic.co/observability-ci/apm-agent-nodejs:$VER` images are just broken:

This got me looking at the apm-agent-nodejs Jenkins tests. The tests for node versions with these broken docker images are incorrectly testing with node v8.17. For example looking at the log for the "Node.js-16" test step of https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fapm-agent-nodejs-mbp/detail/master/41/pipeline/159

```
[2021-12-21T05:55:33.872Z] + .ci/scripts/test.sh -b release -t  16
[2021-12-21T05:55:33.872Z] Running Agent tests with node v16 (BUILD_TYPE=release, FORCE=false)
...
[2021-12-21T05:56:49.792Z] Creating docker_node_tests_1    ... done
[2021-12-21T05:56:49.792Z] Attaching to docker_node_tests_1
...
[2021-12-21T05:56:49.793Z] node_tests_1     | declare -x TAV=""
[2021-12-21T05:56:49.793Z] node_tests_1     | declare -x YARN_VERSION="1.21.1"
[2021-12-21T05:56:49.793Z] node_tests_1     | uid=1167 gid=1168 groups=1168
[2021-12-21T05:56:49.793Z] node_tests_1     | v8.17.0
[2021-12-21T05:56:49.793Z] node_tests_1     | 6.13.4
...
```

**Comment by trentm** [comment]
> Is there a reason to have the `docker.elastic.co/observability-ci/apm-agent-nodejs:$VER` images? 

I think this is what you were saying in your earlier comment:

> OTOH, I've just seen [elastic/apm-agent-nodejs@408bffd#diff-3d76e86295bc21f0f76a699d343b7a20d1a79f40b270e06a6dc3863d713a81b5](https://github.com/elastic/apm-agent-nodejs/commit/408bffdeb4e44ad26f5f4086720ba725ebf19db8#diff-3d76e86295bc21f0f76a699d343b7a20d1a79f40b270e06a6dc3863d713a81b5) therefore the retagging might not be needed anymore.

**Comment by v1v** [comment]
This is now working after removing the tagging for node:$VER.

See https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fecs-logging-nodejs-mbp/detail/main/4/pipeline

I think we can close this one now. OTOH, elastic/infra is a private repo

**Comment by trentm** [comment]
> I think we can close this one now. 

Sounds good to me. Thanks!
