### ISSUE TITLE
[@elastic/ecs-pino-format] support for pino 7+

### ISSUE THREAD

**Issue by ejhayes** [elastic/ecs-logging-nodejs#115]
It appears that `@elastic/ecs-pino-format` does not work with pino 7+

**Comment by trentm** [comment]
@ejhayes Thanks for the issue, and my apologies for not having responded in so long.

While this package *does* have `pino@6` in its **devDependencies**, it looks to me like `@elastic/ecs-pino-format` *does* work with pino@7 and pino@8.  Please seem my recent comment at https://github.com/elastic/ecs-logging-nodejs/pull/131#issuecomment-1780123187

Please re-open this issue if you can show me an example of `@elastic/ecs-pino-format` failing with pino@7 with specifics. Thanks.
