### ISSUE TITLE
Ability to exclude Authorization header parameters from log

### ISSUE THREAD

**Issue by fidgi** [elastic/ecs-logging-nodejs#116]
Hi,

Is there a way to not output request Authorization header parameters (ex: the value of the Authorization Basic parameter) in log depending on the log level ?

Regards

**Comment by lancegliser** [comment]
There's work on this that's been tracked in #57

**Comment by trentm** [comment]
@fidgi Thanks very much for the issue and my apologies for taking so long to reply. This should now be possible as of recently merged #161.  However, I still need to get a release out with this. I am targeting next week for a release.

See the full example at https://github.com/elastic/ecs-logging-nodejs/blob/main/packages/ecs-winston-format/examples/redact-fields.js
