### ISSUE TITLE
"@elastic/ecs-pino-format" has a deprecated transitive dependency "string-similarity"

### ISSUE THREAD

**Issue by staskorz** [elastic/ecs-logging-nodejs#144]
"@elastic/ecs-pino-format" depends on "@elastic/ecs-helpers", which depends on an old version of "fast-json-stringify", which depends on "string-similarity" which is [deprecated](https://www.npmjs.com/package/string-similarity):

```
@elastic/ecs-pino-format > @elastic/ecs-helpers > fast-json-stringify > string-similarity@4.0.4: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
```

Newer versions of "fast-json-stringify" do not depend on "string-similarity" any more.

**Comment by trentm** [comment]
See discussion at https://github.com/elastic/ecs-logging-nodejs/pull/145
This'll require a major ver bump to raise the min supported Node.js to v14.17.0.
I hope to do so relatively soon.

**Comment by trentm** [comment]
> This'll require a major ver bump to raise the min supported Node.js to v14.17.0.

Update from #155: this will *not* require a major version bump. Releases v1.5.0 and later will have this fix.
