### ISSUE TITLE
Can I help? :champagne:

### ISSUE THREAD

**Issue by ddolcimascolo** [elastic/ecs-logging-nodejs#45]
Hi @trentm and other contributors !

I noticed some momentum around Node repositories in the @elastic organization, mostly this one and https://github.com/elastic/apm-agent-nodejs and I just wanted to propose my help. I've contributed already (https://github.com/elastic/apm-agent-nodejs/pull/1909, https://github.com/elastic/apm-nodejs-http-client/pull/117) and I do have a strong understanding of Elasticsearch concepts through more than 5 years using it in production, mostly with Node backends.

@stordata we're in the process of improving the observability of our apps (better logs, more detailed APM transactions, wider distributed tracing, etc.) and we'll be using use https://github.com/elastic/ecs-logging-js soon.

So, should you need any help making it towards a 1.0 release, just ask !

Regards,
David

**Comment by trentm** [comment]
@ddolcimascolo Thanks, and hi!  I appreciate the offer of help.  For the logging libs: I'm working towards a 1.0 release very soon (within a week I think). Published docs should be up at https://www.elastic.co/guide/en/ecs-logging/nodejs/current/intro.html later today. Then I hope to get to the few open PRs and issues and then tag this all 1.0.

I'd appreciate feedback on the docs and usage of the recentish changes I've made.
If you are keen and a Bunyan user there is this feature request which would be nice: https://github.com/elastic/ecs-logging/issues/11 (though not a requirement).

What logging framework(s) are you using at stordata?

**Comment by ddolcimascolo** [comment]
Winston 3.

I'll read the new docs and report here, anyway thanks for improving the Elastic NodeJS ecosystem!

**Comment by ddolcimascolo** [comment]
Docs LGTM, I'll give the code a try ASAP and report here

**Comment by ddolcimascolo** [comment]
Hi @trentm

I just gave 1.0.0 a try and I managed to get a working Kibana logs UI showing my Winston logs in minutes. Congrats for shipping these nice helpers! 

I've been a bit disappointed to find out that error.stack_trace is not yet supported in Kibana, but that'll be implemented soon 🤞 see https://github.com/elastic/kibana/issues/46211

Also when sending `{ res }` in metadata the logs UI show the log line as if it was an access log, I suppose this is because it detects a few HTTP response fields, anyway it's no big deal.

I've put together a Winston config for a Nodejs server running as a multi instance PM2 cluster, using the ECS field `service.node.name` as the instance ID. That might be interesting to document as an example, if you think that's worth it I can open a docs PR with that. Let me know.

Cheers, 
David

**Comment by trentm** [comment]
> That might be interesting to document as an example

I think it would be great to have a more real/concrete example in there. Depending on the size I'm not sure if we'd want it on the https://www.elastic.co/guide/en/ecs-logging/nodejs/master/winston.html page or a separate page linked from there. A PR would be a good start.

I've not used pm2. I'd be interested to learn about it. I'm also curious your experiences with [the APM agent](https://github.com/elastic/apm-agent-nodejs) and pm2, assuming you use the APM agent and there is any adverse interaction there with pm2.

> show the log line as if it was an access log,

Does that cause some issue with using the Logs app?

**Comment by trentm** [comment]
Please re-open if you feel there is more to discuss here. I'm doing some issue spring cleaning. :)

**Comment by felixbarny** [comment]
> I've been a bit disappointed to find out that error.stack_trace is not yet supported in Kibana, but that'll be implemented soon 🤞

BTW, I've created a PR to add `error.stack_trace` to the Logs UI: https://github.com/elastic/kibana/pull/94906

I'm not a Kibana expert though.
