### ISSUE TITLE
Logging an object that contains an 'event' key, crashes things.

### ISSUE THREAD

**Issue by boneill42** [elastic/ecs-logging-nodejs#58]
When trying to log an object that has `"event":"processed"` as a key, things bomb with a:
```
/Users/bone/git/snapyr-io-plane/node_modules/@elastic/ecs-winston-format/index.js:105
      ecsFields.event.dataset = serviceName + '.log'
                              ^
TypeError: Cannot create property 'dataset' on string 'processed'
```

I think you want to add "event" as a reserved field here:
https://github.com/elastic/ecs-logging-nodejs/blob/master/loggers/winston/index.js#L38

Because you depend on it here:
https://github.com/elastic/ecs-logging-nodejs/blob/master/loggers/winston/index.js#L104

And if there are conflicts, you probably want to handle them in an else statement here:
https://github.com/elastic/ecs-logging-nodejs/blob/master/loggers/winston/index.js#L78

There, you could at the very least log.Warn about it.  Ideally, maybe even chose a different fieldName  to put event information.

**Comment by trentm** [comment]
Oops, ^^ that commit meant to refer to #59, not this one.

**Comment by trentm** [comment]
A version v1.1.0 has been published with this fix. Thanks for the issue!
