### ISSUE TITLE
doubt: are there plans to add type definitions?

### ISSUE THREAD

**Issue by gerardolima** [elastic/ecs-logging-nodejs#77]
Are there plans to add type definitions?

**Comment by brtheb** [comment]
See https://github.com/elastic/ecs-logging-nodejs/pull/82

**Comment by trentm** [comment]
@gerardolima Sorry, I hadn't seen this issue earlier.  As @brtheb linked above, there are types for the Pino-related package (though not in a release yet). Was is the pino package, or a separate logger package that you were most interested in?

**Comment by miclud** [comment]
Hi, I'm interested in types for the winston logger.
Any plans for it?

**Comment by trentm** [comment]
@miclud (and others), thanks for all the requests. I've added this to a (somewhat fluid) upcoming milestone. Given the interest I'll prioritize this.  PRs (similar to #82) are definitely welcome.

**Comment by trentm** [comment]
@elastic/ecs-winston-format@1.3.0 and  @elastic/ecs-pino-format@1.3.0 have been published with TypeScript types. A PR would be welcome for  @elastic/ecs-morgan-format
