### ISSUE TITLE
Namespace defaultMeta with either labels or tags.

### ISSUE THREAD

**Issue by rdifrango** [elastic/ecs-logging-nodejs#97]
I noticed when I was working with the ECS NodeJS loggers that Metadata fields weren't name spaced.  

I can see one of three scenario's:

1. Make the default namespace be `labels` per [https://www.elastic.co/guide/en/ecs/current/ecs-base.html](Base Fields)
2. Make the default namespace be `tags` per [https://www.elastic.co/guide/en/ecs/current/ecs-base.html](Base Fields) 
3. Allow for a customized namespace via a configuration parameter.

Here's an example configuration:

```javascript
const logger = winston.createLogger({
   format: ecsFormat(),
   level: "debug",
   defaultMeta: {
      defaultMeta: {
         'environment': 'dev'
      }
   },
   transports: [
      new winston.transports.Console()
   ]
})
```

and a resulting output:

```json
{
   "@timestamp": "2021-08-20T15:43:32.147Z",
   "log.level": "debug",
   "message": "Example with the default Meta Data fields.",
   "ecs": {
      "version": "1.6.0"
   },
   "environment": "dev"
}
```

**Comment by trentm** [comment]
Yes, agreed. Would you mind moving to https://github.com/elastic/ecs-logging-nodejs/issues/68 -- which I believe is the same general issue?

**Comment by rdifrango** [comment]
@trentm Moved my comment over there so feel free to close this.

**Comment by trentm** [comment]
Thanks.
